Design home and about page
aimalamiri/CoWorking-Space pull request #1
Opened 2022-04-13 14:38 UTC by aimalamiri

2022-04-13 23:31 UTC, MeqdamAlqudah requested changes
Hi @aimalamiri , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
![](https://media1.giphy.com/media/MSBL2S3tcyCUzuLV2S/200w.webp?cid=ecf05e47qj17t333muzanx1k6wfzlwi5kkmrc6gttfum3xm1&rid=200w.webp&ct=g)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-13 23:31 UTC, MeqdamAlqudah commented on about.html
> +          <div class="collapse navbar-collapse" id="navbarNav">
- [x] Please make sure to have an option in the navbar that sends the user to the home page 
![image](https://user-images.githubusercontent.com/74744787/163282627-151c9019-76cc-46f3-9048-4b338cca7007.png) I know this is not in the design but you have a home page 
the user should be able to switch between the home and the about page

2022-04-13 23:31 UTC, MeqdamAlqudah commented on about.html
> +    </footer>
- [ ] Please make sure that the footer matches Behance design in the mobile version the logo should be aligned to the right and the text to the left
 
| Your design | Behance |
| ------------- | --------- |
| ![image](https://user-images.githubusercontent.com/74744787/163283702-c3ba7c58-621f-46c9-ba0b-36cc9357abd1.png) | ![image](https://user-images.githubusercontent.com/74744787/163283596-7cf3e25a-ad21-45a3-833d-bd4869802b18.png) |

2022-04-13 23:31 UTC, MeqdamAlqudah commented on about.html
> +                non.
- [ ] Please make sure that the text matches the one in the Behance design 

| Your design | Behance |
| ------------- | --------- |
| ![image](https://user-images.githubusercontent.com/74744787/163285070-eba63081-1a5e-49aa-acdd-29903aa2a690.png) | ![image](https://user-images.githubusercontent.com/74744787/163285133-2fd52b32-478a-475a-980b-7083e0882bc2.png) |
| Please make sure that you are using the same font color ,the same text,the same font family (Cocogoose, Lato)  |

2022-04-13 23:31 UTC, MeqdamAlqudah commented on index.html
> +            </div>
- [ ] Please make sure to Implement the hovering technique is in Behance design 

| Your design | Behance |
| ------------- | --------- |
| ![image](https://user-images.githubusercontent.com/74744787/163285834-138d8a1b-c904-4c23-ab99-3f08793b4046.png) | ![image](https://user-images.githubusercontent.com/74744787/163285872-7466680f-1a65-4b85-a1a6-44af55a3d227.png) |
if you notice the design you can see how the border turns to be white when the user do an over mouse event

2022-04-14 10:55 UTC, aimalamiri commented on about.html
> +          <div class="collapse navbar-collapse" id="navbarNav">
In the task, Microverse asked me to give a link to the home page with the logo, so when the user clicks on the logo it'll redirect the user to the homepage.

2022-04-14 11:31 UTC, MeqdamAlqudah commented on about.html
> +          <div class="collapse navbar-collapse" id="navbarNav">
@aimalamiri sure aimalamiri most of the websites send you to the home page when you press the logo(i.e that is why Microverse told you to put a link to the home page when the user presses the logo ), but it is also required to put a home page link so the user can navigate easily between the home page and the about page i.e it should be simple to the user remember KISS principle.

2022-04-14 12:04 UTC, codepantha approved these changes
Hi @aimalamiri 👋

## STATUS: APPROVED ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif"/>

### To highlight 💡 
- Beautiful and responsive UI ✅ 
- Descriptive PR ✅ 
- Meaningfull commit messages ✅ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-14 12:08 UTC, merged